variables:
  GIT_STRATEGY: clone

stages:
  - Build Dev Docker Image
  - Deploy Dev
  - Build Prod Docker Image
  - Deploy Production

dockerconcordcidev:
  dependencies: []
  stage: Build Dev Docker Image
  script:
    - "$(aws ecr get-login --no-include-email --region ca-central-1)"
    - "docker pull 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-dev:latest || true"
    - 'docker build --cache-from 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-dev:latest --build-arg NODE_ENV="production" --build-arg BUILD_ENV="development" -t clubkitchen-dev .'
    - "docker tag clubkitchen-dev 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-dev:$CI_COMMIT_SHA && docker tag clubkitchen-dev 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-dev:latest"
    - "docker push 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-dev:$CI_COMMIT_SHA && docker push 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-dev:latest"
  tags:
    - concord_dev
  only:
    - dev@web/clubkitchen.ca

dockerprod:
  dependencies: []
  stage: Build Prod Docker Image
  script:
    - "$(aws ecr get-login --no-include-email --region ca-central-1)"
    - "docker pull 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-prod:latest || true"
    - 'docker build --cache-from 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-prod:latest --build-arg NODE_ENV="production" --build-arg BUILD_ENV="production" -t clubkitchen-prod .'
    - "docker tag clubkitchen-prod 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-prod:$CI_COMMIT_SHA && docker tag clubkitchen-prod 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-prod:latest"
    - "docker push 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-prod:$CI_COMMIT_SHA && docker push 406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-prod:latest"
  when: manual
  tags:
    - concord_prod
  only:
    - dev@web/clubkitchen.ca

Deploy Production:
  variables:
    GIT_STRATEGY: none
  dependencies: []
  stage: Deploy Production
  script:
    - echo "Do this manually for now"
    - echo "kubectl set image deployment/clubkitchen-prod clubkitchen-prod=406865557654.dkr.ecr.ca-central-1.amazonaws.com/clubkitchen-prod:$CI_COMMIT_SHA"
    - "false"
  when: manual
  tags:
    - concord_prod
  only:
    - dev@web/clubkitchen.ca
  environment: production
